version: "3.8"
services:
  local-client:
    build:
      dockerfile: ./.docker/images/local-client.Dockerfile
    image: local-client
    privileged: true
    env_file:
      - .env
    environment:
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - ./LocalClient:/app
      - ./.docker/volumes/mp3s:/app/media
    ports:
      - 8080:8080

  web-client:
    build:
      dockerfile: ./.docker/images/web-client.Dockerfile
    image: web-client
    entrypoint: sh -c "npm i && npm run dev"
    working_dir: /app
    environment:
      - XDG_RUNTIME_DIR=/tmp
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - ./WebClient:/app
      - /run/user/1000/pipewire-0:/tmp/pipewire-0

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: playlist_db
    ports:
      - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    user: '1000'
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres:
  pgadmin: